title: "Novemberizing"
description: "Novemberizing's Blog"
baseurl: "/"
url: "https://novemberizing.github.io"
author: "Hyunsik Park"
email: "novemberizing@gmail.com"
website: "https://novemberizing.github.io"
linkedin: "novemberizing"
github: "iticworld"
twitter: "@novemberizing"

paginate: 1
paginate_path: "/blog/page:num/"

words_per_minute: 200

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
mathjax: true
highlighter: rouge
google_analytics: 'G-10W4MY2Q8K'

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - HISTORY.md
  - README.md
  - /temp

future: true