title: "Novemberizing"
description: "Novemberizing's Blog"
baseurl: "/"
url: "https://novemberizing.github.io"
author: "Hyunsik Park"
email: "novemberizing@gmail.com"
website: "https://novemberizing.github.io"
linkedin: "novemberizing"
github: "iticworld"
twitter: "@novemberizing"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 1
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'blog'

words_per_minute: 200

markdown: kramdown
mathjax: true
highlighter: rouge
google_analytics: 'G-10W4MY2Q8K'

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - HISTORY.md
  - README.md

future: true